// flow-typed signature: e4abd8138b67bd70cde62a1b7ebd534c
// flow-typed version: <<STUB>>/monet_v0.9.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'monet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'monet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'monet/dist/monet-pimp' {
  declare module.exports: any;
}

declare module 'monet/dist/monet-pimp.min' {
  declare module.exports: any;
}

declare module 'monet/dist/monet' {
  declare module.exports: any;
}

declare module 'monet/dist/monet.min' {
  declare module.exports: any;
}

declare module 'monet/prepublish-test/browser-global' {
  declare module.exports: any;
}

declare module 'monet/prepublish-test/node-global' {
  declare module.exports: any;
}

declare module 'monet/prepublish-test/node-regular' {
  declare module.exports: any;
}

// Filename aliases
declare module 'monet/dist/monet-pimp.js' {
  declare module.exports: $Exports<'monet/dist/monet-pimp'>;
}
declare module 'monet/dist/monet-pimp.min.js' {
  declare module.exports: $Exports<'monet/dist/monet-pimp.min'>;
}
declare module 'monet/dist/monet.js' {
  declare module.exports: $Exports<'monet/dist/monet'>;
}
declare module 'monet/dist/monet.min.js' {
  declare module.exports: $Exports<'monet/dist/monet.min'>;
}
declare module 'monet/prepublish-test/browser-global.js' {
  declare module.exports: $Exports<'monet/prepublish-test/browser-global'>;
}
declare module 'monet/prepublish-test/node-global.js' {
  declare module.exports: $Exports<'monet/prepublish-test/node-global'>;
}
declare module 'monet/prepublish-test/node-regular.js' {
  declare module.exports: $Exports<'monet/prepublish-test/node-regular'>;
}
