// flow-typed signature: 600e4f0ee6c406d2e04a51ed3be7092c
// flow-typed version: <<STUB>>/redux-persist-transform-immutable_v5.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-transform-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-transform-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redux-persist-transform-immutable/index' {
  declare module.exports: $Exports<'redux-persist-transform-immutable'>;
}
declare module 'redux-persist-transform-immutable/index.js' {
  declare module.exports: $Exports<'redux-persist-transform-immutable'>;
}
