// flow-typed signature: bff7a21fa1027bcd4528d55fb49678a3
// flow-typed version: <<STUB>>/redux-first-router_v2.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-first-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-first-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-first-router/dist/action-creators/addRoutes' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/action-creators/historyCreateAction' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/action-creators/middlewareCreateAction' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/action-creators/middlewareCreateNotFoundAction' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/action-creators/redirect' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/connectRoutes' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/flow-types' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/index' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/actionToPath' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/attemptCallRouteThunk' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/canUseDom' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/changePageTitle' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/confirmLeave' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/createThunk' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/isLocationAction' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/isReactNative' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/isRedirectAction' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/isServer' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/nestAction' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/objectValues' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/pathnamePlusSearch' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/pathToAction' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/pure-utils/setKind' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/reducer/createLocationReducer' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/redux-first-router' {
  declare module.exports: any;
}

declare module 'redux-first-router/dist/redux-first-router.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-first-router/dist/action-creators/addRoutes.js' {
  declare module.exports: $Exports<'redux-first-router/dist/action-creators/addRoutes'>;
}
declare module 'redux-first-router/dist/action-creators/historyCreateAction.js' {
  declare module.exports: $Exports<'redux-first-router/dist/action-creators/historyCreateAction'>;
}
declare module 'redux-first-router/dist/action-creators/middlewareCreateAction.js' {
  declare module.exports: $Exports<'redux-first-router/dist/action-creators/middlewareCreateAction'>;
}
declare module 'redux-first-router/dist/action-creators/middlewareCreateNotFoundAction.js' {
  declare module.exports: $Exports<'redux-first-router/dist/action-creators/middlewareCreateNotFoundAction'>;
}
declare module 'redux-first-router/dist/action-creators/redirect.js' {
  declare module.exports: $Exports<'redux-first-router/dist/action-creators/redirect'>;
}
declare module 'redux-first-router/dist/connectRoutes.js' {
  declare module.exports: $Exports<'redux-first-router/dist/connectRoutes'>;
}
declare module 'redux-first-router/dist/flow-types.js' {
  declare module.exports: $Exports<'redux-first-router/dist/flow-types'>;
}
declare module 'redux-first-router/dist/index.js' {
  declare module.exports: $Exports<'redux-first-router/dist/index'>;
}
declare module 'redux-first-router/dist/pure-utils/actionToPath.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/actionToPath'>;
}
declare module 'redux-first-router/dist/pure-utils/attemptCallRouteThunk.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/attemptCallRouteThunk'>;
}
declare module 'redux-first-router/dist/pure-utils/canUseDom.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/canUseDom'>;
}
declare module 'redux-first-router/dist/pure-utils/changePageTitle.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/changePageTitle'>;
}
declare module 'redux-first-router/dist/pure-utils/confirmLeave.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/confirmLeave'>;
}
declare module 'redux-first-router/dist/pure-utils/createThunk.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/createThunk'>;
}
declare module 'redux-first-router/dist/pure-utils/isLocationAction.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/isLocationAction'>;
}
declare module 'redux-first-router/dist/pure-utils/isReactNative.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/isReactNative'>;
}
declare module 'redux-first-router/dist/pure-utils/isRedirectAction.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/isRedirectAction'>;
}
declare module 'redux-first-router/dist/pure-utils/isServer.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/isServer'>;
}
declare module 'redux-first-router/dist/pure-utils/nestAction.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/nestAction'>;
}
declare module 'redux-first-router/dist/pure-utils/objectValues.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/objectValues'>;
}
declare module 'redux-first-router/dist/pure-utils/pathnamePlusSearch.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/pathnamePlusSearch'>;
}
declare module 'redux-first-router/dist/pure-utils/pathToAction.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/pathToAction'>;
}
declare module 'redux-first-router/dist/pure-utils/setKind.js' {
  declare module.exports: $Exports<'redux-first-router/dist/pure-utils/setKind'>;
}
declare module 'redux-first-router/dist/reducer/createLocationReducer.js' {
  declare module.exports: $Exports<'redux-first-router/dist/reducer/createLocationReducer'>;
}
declare module 'redux-first-router/dist/redux-first-router.js' {
  declare module.exports: $Exports<'redux-first-router/dist/redux-first-router'>;
}
declare module 'redux-first-router/dist/redux-first-router.min.js' {
  declare module.exports: $Exports<'redux-first-router/dist/redux-first-router.min'>;
}
